# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Oxford-Calendar
version:      2.02
version_from: lib/Oxford/Calendar.pm
installdirs:  site
requires:
    Date::Calc:                    0
    Test::Exception:               0
    Test::More:                    0
    Text::Abbrev:                  0
    Time::Seconds:                 0
    YAML:                          0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
